# Site settings
title: Rohan Ranshinge
email: rranshinge@ucdavis.edu
url: https://rohanranshinge.github.io
description: "Business Analytics student at UC Davis"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Rohan Ranshinge

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Linkedin
    url: https://Linkedin.com/rohanranshinge
  - title: github
    url: https://github.com/RohanRanshinge
# Build settings
markdown: kramdown
permalink: pretty
