project:
  type: website
  output-dir: public

website:
  title: "Main missions and Side Quests"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
format:
  html:
    theme: cyborg
